# name: Build and Push to Docker Hub
#
# on:
#   push:
#     branches:
#       - main
#
# env:
#   IMAGE_NAME: growfatlikeme/flask-app # Replace with your Docker Hub repo name
#
# jobs:
#   dockerhub:
#     name: Build & Push to Docker Hub
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#       - name: Build and tag image
#         run: |
#           docker build -t $IMAGE_NAME:latest \
#                        -t $IMAGE_NAME:${{ github.sha }} .
#
#       - name: Push image to Docker Hub
#         run: |
#           docker push $IMAGE_NAME:latest
#           docker push $IMAGE_NAME:${{ github.sha }}
