name: Deploy to Amazon ECS

on:
  push:
    branches:
      - dev
      - uat

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ vars.ENV }} environment..."
          echo "API_TOKEN is ${{ secrets.API_TOKEN }}"

      - name: Set up Python (optional if building requirements.txt)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Create ECR Repository
        run: |
          # Check if repository exists
          if ! aws ecr describe-repositories --repository-names growfat-flask-private-repository &> /dev/null; then
            echo "Creating ECR repository: growfat-flask-private-repository"
            aws ecr create-repository --repository-name growfat-flask-private-repository --image-scanning-configuration scanOnPush=true
          else
            echo "ECR repository already exists: growfat-flask-private-repository"
          fi

      - name: Build and push Docker image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
          platforms: linux/amd64
          provenance: false

      - name: Create SSM Parameter and Secrets Manager Secret
        id: create-secrets
        run: |
          # Create SSM Parameter
          echo "Creating SSM parameter..."
          aws ssm put-parameter \
            --name "/growfat/config" \
            --type "String" \
            --value "${{ secrets.MY_APP_CONFIG }}" \
            --overwrite

          SSM_PARAM_ARN="arn:aws:ssm:ap-southeast-1:$(aws sts get-caller-identity --query Account --output text):parameter/growfat/config"
          echo "SSM Parameter ARN: $SSM_PARAM_ARN"
          echo "SSM_PARAM_ARN=$SSM_PARAM_ARN" >> $GITHUB_OUTPUT

          # Create Secrets Manager Secret
          echo "Creating Secrets Manager secret..."
          SECRET_ARN=$(aws secretsmanager create-secret \
            --name "growfat/db_password" \
            --secret-string "${{ secrets.MY_DB_PASSWORD }}" \
            --query 'ARN' --output text 2>/dev/null || \
            aws secretsmanager update-secret \
            --secret-id "growfat/db_password" \
            --secret-string "${{ secrets.MY_DB_PASSWORD }}" \
            --query 'ARN' --output text)

          echo "Secrets Manager Secret ARN: $SECRET_ARN"
          echo "SECRET_ARN=$SECRET_ARN" >> $GITHUB_OUTPUT

      - name: Create and register task definition
        run: |
          cat > task-definition.json << EOF
          {
            "family": "growfat-task",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "512",
            "memory": "1024",
            "executionRoleArn": "arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):role/growfat-ecs-xray-taskexecutionrole",
            "taskRoleArn": "arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):role/growfat-ecs-xray-taskrole",
            "containerDefinitions": [
              {
                "name": "growfat-flask-container",
                "image": "${{ steps.login-ecr.outputs.registry }}/growfat-flask-private-repository:${{ github.sha }}",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {
                    "name": "SERVICE_NAME",
                    "value": "growfat-flask-service"
                  }
                ],
                "secrets": [
                  {
                    "name": "MY_APP_CONFIG",
                    "valueFrom": "${{ steps.create-secrets.outputs.SSM_PARAM_ARN }}"
                  },
                  {
                    "name": "MY_DB_PASSWORD",
                    "valueFrom": "${{ steps.create-secrets.outputs.SECRET_ARN }}"
                  }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/growfat-task",
                    "awslogs-region": "ap-southeast-1",
                    "awslogs-stream-prefix": "flask-app"
                  }
                }
              },
              {
                "name": "xray-sidecar",
                "image": "amazon/aws-xray-daemon:latest",
                "essential": false,
                "portMappings": [
                  {
                    "containerPort": 2000,
                    "protocol": "udp"
                  }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/growfat-task",
                    "awslogs-region": "ap-southeast-1",
                    "awslogs-stream-prefix": "xray-sidecar"
                  }
                }
              }
            ]
          }
          EOF
          
          # Register the task definition
          aws ecs register-task-definition --cli-input-json file://task-definition.json
          
          # Update the service to use the new task definition
          aws ecs update-service \
            --cluster growfat-flask-ecs \
            --service growfat-service \
            --task-definition growfat-task
